baseURL: https://blog.bitqiu.cc/
title: Bitqiu
paginate: 10
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production
  title: Bitqiu blog
  # description: "ExampleSite description"
  # keywords: [Blog, Portfolio, PaperMod]
  author: Bitqiu
  
  images: ["blog-cover.png"]

  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    # favicon: "<link / abs url>"
    # favicon16x16: "<link / abs url>"
    # favicon32x32: "<link / abs url>"
    # apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "apple-touch-icon.png"

  # profile mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: Bitqiu
    # imageUrl: "#"
    # imageWidth: 120
    # imageHeight: 120
    # imageTitle: my image
    buttons:
      - name: Archives
        url: archives
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  socialIcons:
    # - name: twitter
    #   url: "https://twitter.com/"
    - name: stackoverflow
      url: "https://stackoverflow.com/users/6186521/q-bit"
    - name: github
      url: "https://github.com/bitqiu"

  editPost:
      URL: "https://github.com/bitqiu/bitqiu.github.io/tree/main/content"
      Text: "Suggest Changes" # edit text
      appendFilePath: true # to append file path to Edit link

    
menu:
  main:
    - name: Archive
      url: archives
      weight: 1
    - name: Posts
      url: posts
      weight: 2
    - name: Tags
      url: tags
      weight: 3
    - name: Search
      url: search
      weight: 20
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
markup:
    goldmark:
      renderer:
        unsafe: true
    # highlight:
    #     # anchorLineNos: true
    #     codeFences: true
    #     guessSyntax: true
    #     lineNos: true
    #     style: monokai
